export const Price = [
  {
    objectId: 1,
    name: "Business",
    amount: "$199 / year",
    discript: "Perfect for using in a Business website or a client project.",
    user: "5 Users",
    component: "All UI components",
    lifeTime: "Lifetime access",
    update: "Free updates",
    uses: "Use on 3 (Three) project",
    suport: "4 Months support",
    button: "choose business",
  },

  {
    objectId: 2,
    name: "Business",
    amount: "$199 / year",
    discript: "Perfect for using in a Business website or a client project.",
    user: "5 Users",
    component: "All UI components",
    lifeTime: "Lifetime access",
    update: "Free updates",
    uses: "Use on 3 (Three) project",
    suport: "4 Months support",
    button: "choose business",
  },
  {
    objectId: 3,
    name: "Business",
    amount: "$199 / year",
    discript: "Perfect for using in a Business website or a client project.",
    user: "5 Users",
    component: "All UI components",
    lifeTime: "Lifetime access",
    update: "Free updates",
    uses: "Use on 3 (Three) project",
    suport: "4 Months support",
    button: "choose business",
  },
];
